# permissions for end users to edit dgljobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dgljob-editor-role
rules:
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs/status
  verbs:
  - get
