
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs/finalizers
  verbs:
  - update
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs/status
  verbs:
  - get
  - patch
  - update
