# --------------------------------------------------
# - Single configuration deployment YAML for DGL-Operator
# - Include:
#      CRD deployment
#      Namespace deployment
#      RBAC deployment
#      DGL-operator container deployment set
# --------------------------------------------------
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: dgljobs.qihoo.net
spec:
  additionalPrinterColumns:
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  group: qihoo.net
  version: v1alpha1
  scope: Namespaced
  names:
    plural: dgljobs
    singular: dgljob
    kind: DGLJob
    shortNames:
    - dj
    - dglj
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            # slotsPerWorker:
            #   type: integer
            #   minimum: 1
            dglReplicaSpecs:
              properties:
                Launcher:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
                      maximum: 1
                Worker:
                  properties:
                    replicas:
                      type: integer
                      minimum: 1
---
apiVersion: v1
kind: Namespace
metadata:
  name: dgl-operator
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dgl-operator
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - list
  - watch
  - update
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
  - delete
  - update
  - patch
# This is needed for the launcher Role.
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - list
  - watch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - qihoo.net
  resources:
  - dgljobs
  - dgljobs/finalizers
  - dgljobs/status
  verbs:
  - "*"
- apiGroups:
  - scheduling.incubator.k8s.io
  - scheduling.sigs.dev
  - scheduling.volcano.sh
  resources:
  - queues
  - podgroups
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dgl-operator
  namespace: dgl-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dgl-operator
  namespace: dgl-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dgl-operator
subjects:
- kind: ServiceAccount
  name: dgl-operator
  namespace: dgl-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgl-operator
  namespace: dgl-operator
  labels:
    app: dgl-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgl-operator
  template:
    metadata:
      labels:
        app: dgl-operator
    spec:
      serviceAccountName: dgl-operator
      containers:
      - name: dgl-operator
        image: dgloperator/dgl-operator:v0.1.0
        imagePullPolicy: Always
        args: [
          "--watcher-loop-image",
          "dgloperator/watcher-loop:v0.1.0",
          "--kubectl-download-image",
          "dgloperator/kubectl-download:v0.1.0",
        ]